stages:
  - build

default:
  image: docker:24.0.5-cli
  services:
    - name: docker:24.0.5-dind
      variables:
        HEALTHCHECK_TCP_PORT: "2376"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker info

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_SUBMODULE_FORCE_HTTPS: "true"

build:
  stage: build
  script:
    - DOCKER_TAG=$(echo $CI_COMMIT_BRANCH | sed -E 's|sheriff/||g')
    - docker build -t $CI_REGISTRY_IMAGE:$DOCKER_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$DOCKER_TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

