services:

  ilias:
    build: .
    environment:
      CONFIG_LOCATION: "/tmp/config.json"
      DATABASE_TYPE: innodb
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_DATABASE: ilias
      DATABASE_USER: ilias
      DATABASE_PASSWORD: ilias
      DATABASE_CREATE_DATABASE: true
      HTTP_PATH: http://localhost:8080
      COMMON_CLIENT_ID: ilias-client-id
      FILESYSTEM_DATA_DIR: /var/www/data
      SYSTEMFOLDER_CONTACT_FIRSTNAME: Firstname
      SYSTEMFOLDER_CONTACT_LASTNAME: Lastname
      SYSTEMFOLDER_CONTACT_EMAIL: email
    volumes:
      - ilias-html:/var/www/html
      - ilias-data:/var/www/data
    ports:
      - 8080:80
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ilias
      MARIADB_USER: ilias
      MARIADB_PASSWORD: ilias
      MARIADB_DATABASE: ilias
    volumes:
      - ./mariadb.cnf:/etc/mysql/conf.d/00-custom.cnf:ro
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
  ilias-html:
  ilias-data:
