<?php

/**
 * This file is part of ILIAS, a powerful learning management system
 * published by ILIAS open source e-Learning e.V.
 *
 * ILIAS is licensed with the GPL-3.0,
 * see https://www.gnu.org/licenses/gpl-3.0.en.html
 * You should have received a copy of said license along with the
 * source code, too.
 *
 * If this is not the case or you just want to try ILIAS, you'll find
 * us at:
 * https://www.ilias.de
 * https://github.com/ILIAS-eLearning
 *
 *********************************************************************/

declare(strict_types=1);

namespace ILIAS\Test\Setup;

use ILIAS\Database\PDO\FieldDefinition\ForeignKeyConstraints;

class Test12DBUpdateSteps implements \ilDatabaseUpdateSteps
{
    use TestSettingsSetup;

    protected \ilDBInterface $db;

    public function prepare(\ilDBInterface $db): void
    {
        $this->db = $db;
    }

    public function step_1(): void
    {
        // 1. Ensure that a new column for IP ranges is present
        if (!$this->db->tableColumnExists('tst_test_settings', 'ip_ranges')) {
            $this->db->addTableColumn('tst_test_settings', 'ip_ranges', ['type' => \ilDBConstants::T_TEXT, 'length' => 4000, 'default' => null]);
        }

        // 2. Add ip_range_from to ip_ranges if both ip_range_from and ip_range_to are identical
        $this->db->manipulate(
            'UPDATE tst_test_settings SET ip_ranges = ip_range_from, ip_range_from = NULL, ip_range_to = NULL WHERE ip_range_from == ip_range_to AND ip_range_from IS NOT NULL AND ip_range_to IS NOT NULL'
        );

        // 3. Add ip_range_from to ip_ranges if ip_range_to is empty
        $this->db->manipulate(
            'UPDATE tst_test_settings SET ip_ranges = ip_range_from, ip_range_from = NULL, ip_range_to = NULL WHERE ip_range_from IS NOT NULL AND ip_range_to IS NULL'
        );

        // 4. Add ip_range_to to ip_ranges if ip_range_from is empty
        $this->db->manipulate(
            'UPDATE tst_test_settings SET ip_ranges = ip_range_to, ip_range_from = NULL, ip_range_to = NULL WHERE ip_range_from IS NULL AND ip_range_to IS NOT NULL'
        );
    }

    public function step_2(): void
    {
        // 1. Ensure that a new column for IP ranges is present
        if (!$this->db->tableColumnExists('tst_test_settings', 'ip_ranges')) {
            $this->db->addTableColumn('tst_test_settings', 'ip_ranges', ['type' => \ilDBConstants::T_TEXT, 'length' => 4000, 'default' => null]);
        }

        // 2. Fetch all preexisting IP ranges
        $items = [];
        $res = $this->db->query("SELECT ip_range_from, ip_range_to FROM tst_test_settings WHERE ip_range_from != ip_range_to AND ip_range_from IS NOT NULL AND ip_range_to IS NOT NULL");

        while ($row = $this->db->fetchAssoc($res)) {
            $this->items[] = [
                'ip_range_from' => $row['ip_range_from'],
                'ip_range_to' => $row['ip_range_to']
            ];
        }

        // 3. Check if IP range definition already exists

        foreach ($items as $item) {
            $res = $this->db->query("SELECT definition_id FROM ipaa_data WHERE ip_range_from = " . $item['ip_range_from'] . " AND ip_range_to = " . $item['ip_range_to'] . " LIMIT 1");

            if ($this->db->numRows($res) > 0) {
                // 3a. IP range already exists, add definition_id to tst_test_settings

                $definition_id = $this->db->fetchObject($res)->definition_id;

                $this->db->manipulate(
                    'UPDATE tst_test_settings SET ip_ranges = ' . $this->db->quote('ref_' . $definition_id) . ' WHERE ip_range_from = ' . $this->db->quote($item['ip_range_from']) . ' AND ip_range_to = ' . $this->db->quote($item['ip_range_to'])
                );

            } else {
                // 3b. IP range does not exist, add new entry to ipaa_data and add ref_id to tst_test_settings

                $id = uniqid('ipad_');

                $obj_id = $this->db->nextId('object_data');
                $ref_id = $this->db->nextId('object_reference');

                $this->db->insert('object_data', [
                    'obj_id' => ['integer', $obj_id],
                    'type' => ['text', 'ipad'],
                    'title' => ['text', $id],
                    'description' => ['text', 'This entry was auto-generated by Test12DBUpdateSteps.'],
                ]);

                $this->db->insert('object_reference', [
                    'ref_id' => ['integer', $ref_id],
                    'obj_id' => ['integer', $obj_id]
                ]);

                $this->db->insert('ipaa_data', [
                    'definition_id' => ['integer', $ref_id],
                    'ip_range_from' => ['text', $item['ip_range_from']],
                    'ip_range_to' => ['text', $item['ip_range_to']]
                ]);

                $this->db->manipulate(
                    'UPDATE tst_test_settings SET ip_ranges = ' . $this->db->quote('ref_' . $ref_id) . ' WHERE ip_range_from = ' . $this->db->quote($item['ip_range_from']) . ' AND ip_range_to = ' . $this->db->quote($item['ip_range_to'])
                );
            }

        }

        // 5. Remove columns ip_range_from and ip_range_to
        $this->db->dropTableColumn('tst_test_settings', 'ip_range_from');
        $this->db->dropTableColumn('tst_test_settings', 'ip_range_to');
    }

    public function step_3(): void
    {
        if ($this->db->tableColumnExists('tst_invited_user', 'ip_ranges')) {
            return;
        }

        // 1. Create new column for IP ranges
        $this->db->addTableColumn('tst_invited_user', 'ip_ranges', ['type' => \ilDBConstants::T_TEXT, 'length' => 4000, 'default' => null]);

        $this->db->manipulate(
            'UPDATE tst_invited_user SET ip_ranges = ip_range_from, ip_range_from = NULL, ip_range_to = NULL WHERE ip_range_from == ip_range_to AND ip_range_from IS NOT NULL AND ip_range_to IS NOT NULL'
        );

        $this->db->manipulate(
            'UPDATE tst_invited_user SET ip_ranges = ip_range_from, ip_range_from = NULL, ip_range_to = NULL WHERE ip_range_from IS NOT NULL AND ip_range_to IS NULL'
        );

        $this->db->manipulate(
            'UPDATE tst_invited_user SET ip_ranges = ip_range_to, ip_range_from = NULL, ip_range_to = NULL WHERE ip_range_from IS NULL AND ip_range_to IS NOT NULL'
        );
    }

    public function step_4(): void
    {
        // 1. Ensure that a new column for IP ranges is present
        if (!$this->db->tableColumnExists('tst_invited_user', 'ip_ranges')) {
            $this->db->addTableColumn('tst_invited_user', 'ip_ranges', ['type' => \ilDBConstants::T_TEXT, 'length' => 4000, 'default' => null]);
        }

        // 2. Fetch all preexisting IP ranges
        $items = [];
        $res = $this->db->query("SELECT ip_range_from, ip_range_to FROM tst_invited_user WHERE ip_range_from IS NOT NULL AND ip_range_to IS NOT NULL");

        while ($row = $this->db->fetchAssoc($res)) {
            $this->items[] = [
                'ip_range_from' => $row['ip_range_from'],
                'ip_range_to' => $row['ip_range_to']
            ];
        }

        // 3. Check if IP range definition already exists

        foreach ($items as $item) {
            $res = $this->db->query("SELECT definition_id FROM ipaa_data WHERE ip_range_from = " . $item['ip_range_from'] . " AND ip_range_to = " . $item['ip_range_to'] . " LIMIT 1");

            if ($this->db->numRows($res) > 0) {
                // 3a. IP range already exists, add definition_id to tst_invited_user

                $definition_id = $this->db->fetchObject($res)->definition_id;

                $this->db->manipulate(
                    'UPDATE tst_invited_user SET ip_ranges = ' . $this->db->quote('ref_' . $definition_id) . ' WHERE ip_range_from = ' . $this->db->quote($item['ip_range_from']) . ' AND ip_range_to = ' . $this->db->quote($item['ip_range_to'])
                );

            } else {
                // 3b. IP range does not exist, add new entry to ipaa_data and add ref_id to tst_test_settings

                $id = uniqid('ipad_');

                $obj_id = $this->db->nextId('object_data');
                $ref_id = $this->db->nextId('object_reference');

                $this->db->insert('object_data', [
                    'obj_id' => ['integer', $obj_id],
                    'type' => ['text', 'ipad'],
                    'title' => ['text', $id],
                    'description' => ['text', 'This entry was auto-generated by Test12DBUpdateSteps.'],
                ]);

                $this->db->insert('object_reference', [
                    'ref_id' => ['integer', $ref_id],
                    'obj_id' => ['integer', $obj_id]
                ]);

                $this->db->insert('ipaa_data', [
                    'definition_id' => ['integer', $ref_id],
                    'ip_range_from' => ['text', $item['ip_range_from']],
                    'ip_range_to' => ['text', $item['ip_range_to']]
                ]);

                $this->db->manipulate(
                    'UPDATE tst_test_settings SET ip_ranges = ' . $this->db->quote('ref_' . $ref_id) . ' WHERE ip_range_from = ' . $this->db->quote($item['ip_range_from']) . ' AND ip_range_to = ' . $this->db->quote($item['ip_range_to'])
                );
            }

        }

        // 5. Remove columns ip_range_from and ip_range_to
        $this->db->dropTableColumn('tst_test_settings', 'ip_range_from');
        $this->db->dropTableColumn('tst_test_settings', 'ip_range_to');
    }
}
