<?php return array (
  0 => 'ILIAS\\Authentication\\UserSettings\\Password',
  1 => 'ILIAS\\Awareness\\UserSettings\\ShowStatusInWhoIsOnline',
  2 => 'ILIAS\\Calendar\\UserSettings\\TimeZone',
  3 => 'ILIAS\\Calendar\\UserSettings\\DateFormat',
  4 => 'ILIAS\\Calendar\\UserSettings\\TimeFormat',
  5 => 'ILIAS\\Chatroom\\UserSettings\\AllowOnScreenChatConversations',
  6 => 'ILIAS\\Chatroom\\UserSettings\\BroadcastTyping',
  7 => 'ILIAS\\Contact\\UserSettings\\AllowContactRequest',
  8 => 'ILIAS\\Help\\UserSettings\\Help',
  9 => 'ILIAS\\Language\\UserSettings\\Language',
  10 => 'ILIAS\\Mail\\UserSettings\\IncomingMail',
  11 => 'ILIAS\\Mail\\UserSettings\\NewMailNotification',
  12 => 'ILIAS\\Style\\System\\UserSettings\\Style',
  13 => 'ILIAS\\User\\Settings\\User\\LastVisited',
  14 => 'ILIAS\\User\\Settings\\User\\SessionReminder',
  15 => 'ILIAS\\User\\Settings\\StartingPoint\\Setting',
);